import { createServer } from 'vite';
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const server = await createServer({ server: { host: '127.0.0.1', port: 5178, strictPort: true } });
await server.listen();
let browser;
try {
  browser = await chromium.launch({ executablePath: process.env.BROWSER_PATH, headless: true });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const { mapUrls } = await server.ssrLoadModule('/src/components/FarmLocation.jsx');
  assert.equal(mapUrls(null), null);
  assert.equal(mapUrls({ latitude: 91, longitude: 30 }), null);
  assert.equal(mapUrls({ latitude: NaN, longitude: 30 }), null);
  assert.equal(mapUrls({ latitude: '0', longitude: '0' }), null);
  assert.equal(new URL(mapUrls({ latitude: 0, longitude: 0 }).embed).searchParams.get('marker'), '0,0');
  await page.goto('http://127.0.0.1:5178/agri-news');
  await page.getByRole('button', { name: 'Read More' }).first().click();
  await page.getByRole('dialog').waitFor();
  await page.keyboard.press('Escape');
  await page.goto('http://127.0.0.1:5178/financing');
  await page.getByRole('button', { name: 'Check Eligibility' }).first().click();
  await page.getByRole('dialog').waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Start Application' }).first().click();
  await page.getByLabel('Farm name', { exact: true }).fill('Test farm');
  await page.getByLabel('Amount (USD)', { exact: true }).fill('2000');
  await page.getByLabel('Purpose', { exact: true }).fill('Seed');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: 'View saved draft' }).click();
  await page.getByRole('dialog').getByText('Test farm', { exact: true }).waitFor();
  await page.keyboard.press('Escape');
  await page.goto('http://127.0.0.1:5178/farms');
  assert.equal(await page.getByRole('button', { name: 'View Location', exact: true }).count(), 5);
  await page.getByRole('button', { name: 'View Location', exact: true }).nth(1).click();
  let src = await page.locator('dialog iframe').getAttribute('src');
  assert.equal(new URL(src).searchParams.get('marker'), '-18.13,30.14');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('dialog').count(), 0);
  await page.getByRole('button', { name: 'View Farm Report', exact: true }).first().click();
  await page.getByRole('dialog').getByText('Tendai Moyo', { exact: true }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Filters', exact: true }).click();
  assert.equal(await page.locator('#farm-filters').isVisible(), false);
  await page.goto('http://127.0.0.1:5178/login');
  await page.getByRole('button').filter({ has: page.getByRole('heading', { name: 'Farmer', exact: true }) }).click();
  await page.getByPlaceholder('Enter your email').fill('demo@example.com');
  await page.getByPlaceholder('Enter your password').fill('demo');
  await page.locator('form button[type=submit]').click();
  await page.getByLabel('Go to page').selectOption('farm-profile');
  await page.getByRole('button', { name: 'Edit Profile', exact: true }).click();
  await page.getByLabel('Latitude', { exact: true }).fill('-17.6');
  await page.getByLabel('Longitude', { exact: true }).fill('30.8');
  await page.getByRole('dialog').getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button', { name: 'View Location', exact: true }).click();
  src = await page.locator('dialog iframe').getAttribute('src');
  assert.equal(new URL(src).searchParams.get('marker'), '-17.6,30.8');
  await page.keyboard.press('Escape');
  for (const role of ['Farmer', 'Lender', 'Investor', 'Admin']) {
    await page.locator('.role-switch').getByRole('button', { name: role, exact: true }).click();
    const options = await page.getByLabel('Go to page').locator('option').evaluateAll(els => els.map(el => el.value));
    for (const value of options) {
      await page.getByLabel('Go to page').selectOption(value);
      await page.waitForTimeout(70);
      assert.ok(await page.locator('main').innerText(), role + ':' + value);
    }
  }
  await page.locator('.role-switch').getByRole('button', { name: 'Lender', exact: true }).click();
  await page.getByLabel('Go to page').selectOption('reports');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generate Report', exact: true }).click();
  assert.equal((await downloadPromise).suggestedFilename(), 'Portfolio-report.txt');
  await page.locator('.role-switch').getByRole('button', { name: 'Investor', exact: true }).click();
  await page.getByLabel('Go to page').selectOption('saved');
  await page.getByRole('button', { name: 'Remove', exact: true }).first().click();
  assert.equal(await page.getByRole('button', { name: 'Remove', exact: true }).count(), 1);
  await page.getByRole('button', { name: 'Restore demo opportunities' }).click();
  assert.equal(await page.getByRole('button', { name: 'Remove', exact: true }).count(), 2);
  await page.locator('.sidebar').getByRole('button', { name: 'Sign Out' }).click();
  await page.goto('http://127.0.0.1:5178/farms');
  await page.getByRole('button', { name: 'View Location', exact: true }).first().click();
  src = await page.locator('dialog iframe').getAttribute('src');
  assert.equal(new URL(src).searchParams.get('marker'), '-17.6,30.8');
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'View Location', exact: true }).first().click();
  assert.ok((await page.locator('dialog').boundingBox()).width <= 390);
  await page.keyboard.press('Escape');
  assert.deepEqual(errors, []);
  console.log('PASS: markers, reports, filters, GPS editing/persistence, all dashboard pages, mobile dialog; no runtime errors.');
} finally {
  await browser?.close();
  await server.close();
}
