export const farms = [
  {
    id: 1,
    name: "Nyika Plains Farm",
    farmer: "Tendai Moyo",
    loc: "Mazowe, Mashonaland Central",
    province: "Mashonaland Central",
    district: "Mazowe",
    crop: "Maize",
    size: 120,
    need: 85000,
    ready: "Strong",
    status: "Field Verification",
    date: "18 Aug 2026",
    tenure: "A2 offer letter",
    irrigation: "Borehole + pivot",
    offtaker: "Confirmed",
    score: 82,
    history: [3.1, 4.2, 4.8],
    docs: 5,
  },
  {
    id: 2,
    name: "Mupfure Agri Estate",
    farmer: "Grace Chirwa",
    loc: "Chegutu, Mashonaland West",
    province: "Mashonaland West",
    district: "Chegutu",
    crop: "Soybeans",
    size: 210,
    need: 140000,
    ready: "Strong",
    status: "Verified",
    date: "02 Aug 2026",
    tenure: "Lease",
    irrigation: "Dam access",
    offtaker: "Contracted",
    score: 88,
    history: [2.2, 2.8, 3.3],
    docs: 7,
  },
  {
    id: 3,
    name: "Green Valley Produce",
    farmer: "Farai Nyathi",
    loc: "Mutare, Manicaland",
    province: "Manicaland",
    district: "Mutare",
    crop: "Horticulture",
    size: 38,
    need: 42000,
    ready: "Moderate",
    status: "Document Review",
    date: "11 Aug 2026",
    tenure: "Communal/customary",
    irrigation: "Drip lines",
    offtaker: "Buyer letters",
    score: 68,
    history: [1.4, 1.6, 1.9],
    docs: 4,
  },
  {
    id: 4,
    name: "Umfuli Grain & Livestock",
    farmer: "Blessing Sibanda",
    loc: "Kwekwe, Midlands",
    province: "Midlands",
    district: "Kwekwe",
    crop: "Wheat",
    size: 175,
    need: 120000,
    ready: "Moderate",
    status: "Submitted",
    date: "06 Aug 2026",
    tenure: "Lease",
    irrigation: "Seasonal river",
    offtaker: "Pending",
    score: 61,
    history: [2.7, 3.0, 2.9],
    docs: 3,
  },
  {
    id: 5,
    name: "Mazowe Horticulture Estate",
    farmer: "Rudo Matema",
    loc: "Bindura, Mashonaland Central",
    province: "Mashonaland Central",
    district: "Bindura",
    crop: "Horticulture",
    size: 62,
    need: 65000,
    ready: "Strong",
    status: "Verified",
    date: "15 Aug 2026",
    tenure: "Title deed",
    irrigation: "Borehole + reservoir",
    offtaker: "Supermarket LOI",
    score: 90,
    history: [1.9, 2.4, 2.8],
    docs: 8,
  },
];
export const institutions = [
  {
    name: "AgriCredit Zimbabwe",
    type: "Agricultural lender",
    focus: "Input finance, working capital",
    regions: "National",
    verified: true,
  },
  {
    name: "Zambezi Microfinance",
    type: "Microfinance",
    focus: "Smallholder production loans",
    regions: "Mashonaland, Midlands",
    verified: true,
  },
  {
    name: "Harvest Mutual Insurance",
    type: "Insurance",
    focus: "Weather-index and crop insurance",
    regions: "Pilot districts",
    verified: false,
  },
];
export const products = [
  {
    provider: "AgriCredit Zimbabwe",
    type: "Input finance",
    range: "US$5k–US$150k",
    duration: "6–12 months",
    eligibility: "Verified farm profile, production plan, buyer evidence",
    docs: "ID, land document, crop budget",
  },
  {
    provider: "Zambezi Microfinance",
    type: "Irrigation finance",
    range: "US$2k–US$35k",
    duration: "12–24 months",
    eligibility: "Water source and field verification",
    docs: "Quotations, photos, consent",
  },
  {
    provider: "Harvest Mutual Insurance",
    type: "Crop insurance",
    range: "Seasonal cover",
    duration: "One production cycle",
    eligibility: "Verified GPS boundary and crop declaration",
    docs: "Farm map, crop schedule",
  },
];
export const news = [
  {
    cat: "Markets",
    title:
      "Sample: Grain market dashboard shows rising demand for verified supplier data",
    source: "Farm-Capta Sample Intelligence",
    date: "21 Aug 2026",
  },
  {
    cat: "Weather",
    title:
      "Sample: Irrigation planning remains central for winter wheat financing decisions",
    source: "Farm-Capta Sample Intelligence",
    date: "20 Aug 2026",
  },
  {
    cat: "Finance",
    title:
      "Sample: Lenders increase focus on production evidence and offtaker records",
    source: "Farm-Capta Sample Intelligence",
    date: "18 Aug 2026",
  },
];
